<a href="https://colab.research.google.com/github/SaiCharan29/AD/blob/master/Assignment(04_06_2020).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CSE-221710313019-K Sai Charan

### [Reversing an Array] 
Write a NumPy program to reverse an array (first element becomes last). 
- Original array:
  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
- Reverse array:
  [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [0]:
import numpy as np
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [0]:
ar1=np.arange(12,38)
print(ar1)
ar2=ar1[::-1]
print(ar2)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


### [Make Border 1] 
Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 
- Original array:
- [[ 1. 1. 1. 1. 1.]
- ...................
- [ 1. 1. 1. 1. 1.]]
- 1 on the border and 0 inside in the array
- Expected output:
- [[ 1. 1. 1. 1. 1.]
-  [1. 0. 0. 0. 1.]
- ……………..
-  [1. 0. 0. 0. 1.]
- [ 1. 1. 1. 1. 1.]]


In [0]:
a=int(input())
b=int(input())
a1=np.ones((a,b),dtype="int32")
print(a1)

5
5
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [0]:
a1[1:a-1,1:b-1]=0
print(a1)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### [Membership Test] 
Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
- Expected Output:
 - Array1: [ 0 10 20 40 60]
 - Array2: [0, 40]
 - Compare each element of array1 and array2
 - [ True False False True False]


In [0]:
a1=np.array([0,10,20,40,60])
a2=np.array([0,40])
res=[]
for i in a1:
    if(i in a2):
        res.append(True)
    else:
        res.append(False)
res

[True, False, False, True, False]

### [Set Difference] 
Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.
- Expected Output:
   - Array1: [ 0 10 20 40 60 80]
   - Array2: [10, 30, 40, 50, 70, 90]
- Set difference between two arrays:
    - [ 0 20 60 80]


In [0]:
a1=np.array([0,10,20,40,60,80])
a2=np.array([10,30,40,50,70,90])
s=[]
for i in a1:
    if(i not in a2):
        s.append(i)
s

[0, 20, 60, 80]

### [Formation of Diagonal Matrix] 
Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.
- Expected Output:
    - [[4 0 0 0]
    - [0 5 0 0]
    - [0 0 6 0]
    - [0 0 0 8]]


In [0]:
li=[4,5,6,8]
ar1=np.zeros((4,4),dtype="int32")
for i in range(len(li)):
    ar1[i][i]=li[i]
ar1

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])