<a href="https://colab.research.google.com/github/SaiCharan29/AD/blob/master/Day11(05_06_2020).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from numpy import random
print(random.randint(1,29))
print(random.rand())

22
0.197536844732365


In [0]:
random.randint(100,size=3)

array([21,  9, 81])

In [0]:
random.randint(100,size=(3,4))

array([[89, 44, 96, 94],
       [17, 61,  0,  3],
       [ 0, 36,  9, 73]])

In [0]:
random.randint(100,size=(3,4,2))

array([[[71, 44],
        [28, 11],
        [ 1, 63],
        [62,  6]],

       [[ 8, 20],
        [ 7, 23],
        [ 6, 34],
        [15, 32]],

       [[24,  9],
        [79, 67],
        [81, 30],
        [33, 64]]])

In [0]:
random.rand()

0.9163325425155862

In [0]:
random.rand(2)

array([0.05007264, 0.51328175])

In [0]:
random.rand(2,3)

array([[0.5224699 , 0.92319014, 0.96368917],
       [0.74992578, 0.81336945, 0.93667615]])

In [0]:
a=random.randint(100,size=(4))
a

array([96, 13, 28, 40])

In [0]:
random.choice(a)

40

In [0]:
b=random.randint(100,size=(3,4)).ravel()
b

array([38, 91, 83, 18, 76, 74, 84,  7, 25, 72, 39, 73])

In [0]:
random.choice(b)

25

In [0]:
random.choice([1,2,3,4,5],size=(3,4))

array([[1, 4, 1, 2],
       [1, 3, 3, 5],
       [3, 4, 2, 3]])

In [0]:
import pandas as pd
import numpy as np

In [0]:
dic1={'a':1,'b':2,'c':3,'d':4,'e':5}
dic2={'a':5,'b':6,'c':7,'d':8,'e':9}
data={"First":dic1,"Second":dic2}
df=pd.DataFrame(data,dtype=np.int32)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [0]:
df1={"name":["A","B","C"],"address":["EF","GH","IJ"]}
d=pd.DataFrame(df1)
d

name address
0    A      EF
1    B      GH
2    C      IJ

In [0]:
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([12.3,45.6,78.9,10.2,23.4,56.7,89.01,76.5,54.3,98.7])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data={"col1":s1,"col2":s2,"col3":s3}
dd=pd.DataFrame(data)
dd

col1   col2 col3
0     1  12.30    a
1     2  45.60    b
2     3  78.90    c
3     4  10.20    d
4     5  23.40    e
5     6  56.70    f
6     7  89.01    g
7     8  76.50    h
8     9  54.30    i
9    10  98.70    j

In [0]:
dd["col2"]

0    12.30
1    45.60
2    78.90
3    10.20
4    23.40
5    56.70
6    89.01
7    76.50
8    54.30
9    98.70
Name: col2, dtype: float64

In [0]:
dd[["col2","col3"]]

col2 col3
0  12.30    a
1  45.60    b
2  78.90    c
3  10.20    d
4  23.40    e
5  56.70    f
6  89.01    g
7  76.50    h
8  54.30    i
9  98.70    j

In [0]:
dd.loc[:,"col1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: col1, dtype: int64

In [0]:
dd.loc[1:5,["col1","col2"]]

col1  col2
1     2  45.6
2     3  78.9
3     4  10.2
4     5  23.4
5     6  56.7

In [0]:
type(dd)

pandas.core.frame.DataFrame

In [0]:
dd.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: col1, dtype: int64

In [0]:
dd.iloc[0:4,0:1]

col1
0     1
1     2
2     3
3     4

In [0]:
dd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    10 non-null     int64  
 1   col2    10 non-null     float64
 2   col3    10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [0]:
dd.shape

(10, 3)

In [0]:
dd.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [0]:
dd.index

RangeIndex(start=0, stop=10, step=1)

In [0]:
dd.head()

col1  col2 col3
0     1  12.3    a
1     2  45.6    b
2     3  78.9    c
3     4  10.2    d
4     5  23.4    e

In [0]:
dd.head(2)

col1  col2 col3
0     1  12.3    a
1     2  45.6    b

In [0]:
dd.tail()

col1   col2 col3
5     6  56.70    f
6     7  89.01    g
7     8  76.50    h
8     9  54.30    i
9    10  98.70    j

In [0]:
dd.tail(7)

col1   col2 col3
3     4  10.20    d
4     5  23.40    e
5     6  56.70    f
6     7  89.01    g
7     8  76.50    h
8     9  54.30    i
9    10  98.70    j

In [0]:
dd.sample()

col1  col2 col3
2     3  78.9    c

In [0]:
dd.sample(3)

col1  col2 col3
9    10  98.7    j
7     8  76.5    h
4     5  23.4    e

In [0]:
dd.describe()

col1       col2
count  10.00000  10.000000
mean    5.50000  54.561000
std     3.02765  31.655319
min     1.00000  10.200000
25%     3.25000  28.950000
50%     5.50000  55.500000
75%     7.75000  78.300000
max    10.00000  98.700000

In [0]:
dd=dd.rename(columns={"col1":"1","col2":"2","col3":"3"})
dd

1      2  3
0   1  12.30  a
1   2  45.60  b
2   3  78.90  c
3   4  10.20  d
4   5  23.40  e
5   6  56.70  f
6   7  89.01  g
7   8  76.50  h
8   9  54.30  i
9  10  98.70  j